import {createServer} from 'node:http';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const clean=(v,n=120)=>String(v??'').trim().slice(0,n);
const readJson=(f,d)=>{try{return JSON.parse(readFileSync(f,'utf8'))}catch{return d}};
const writeJson=(f,v)=>{mkdirSync(dirname(f),{recursive:true});const t=`${f}.${process.pid}.tmp`;writeFileSync(t,JSON.stringify(v,null,2)+'\n');renameSync(t,f)};
function getToken(file){mkdirSync(dirname(file),{recursive:true});if(existsSync(file)){const v=readFileSync(file,'utf8').trim();if(v.length>=32)return v}const v=randomBytes(32).toString('base64url');writeFileSync(file,v+'\n',{mode:0o600});return v}
function authorized(req,token){const got=/^Bearer\s+(.+)$/i.exec(String(req.headers.authorization||''))?.[1]||'';const a=Buffer.from(got),b=Buffer.from(token);return a.length===b.length&&timingSafeEqual(a,b)}
function send(res,status,value,type='application/json; charset=utf-8'){const body=Buffer.from(type.startsWith('application/json')?JSON.stringify(value):value);res.writeHead(status,{'content-type':type,'content-length':body.length,'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','content-security-policy':type.startsWith('text/html')?"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'":"default-src 'none'; frame-ancestors 'none'"});res.end(body)}
async function body(req){const parts=[];let size=0;for await(const c of req){size+=c.length;if(size>262144)throw Error('body too large');parts.push(c)}return parts.length?JSON.parse(Buffer.concat(parts)):{} }
function workers(list){return(Array.isArray(list)?list:[]).slice(0,200).map(w=>({id:clean(w?.id||w?.name),displayName:clean(w?.displayName||w?.name||w?.id),backend:clean(w?.backend,40),role:clean(w?.role,60),status:clean(w?.status,40)||'unknown',avatar:clean(w?.avatar,500)||null})).filter(w=>w.id)}
function view(state,staleMs,now=Date.now()){const online=x=>({...x,online:Math.max(0,now-Date.parse(x.lastSeenAt))<=staleMs});return{generatedAt:new Date(now).toISOString(),devices:Object.values(state.devices).map(online).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN')),observers:Object.values(state.observers).map(online).filter(x=>x.online)}}


export function createHubServer({stateFile=resolve('.pi/hub/state.json'),tokenFile=resolve('.pi/hub/token'),staleMs=35000}={}){stateFile=resolve(stateFile);tokenFile=resolve(tokenFile);const token=getToken(tokenFile),state=readJson(stateFile,{version:1,devices:{},observers:{}});state.devices||={};state.observers||={};const persist=()=>writeJson(stateFile,state);const server=createServer(async(req,res)=>{const url=new URL(req.url||'/','http://hub');if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true,service:'ox-factory-device-hub',version:'0.2.0'});if(url.pathname.startsWith('/api/')&&!authorized(req,token))return send(res,401,{error:'invalid or missing bearer token'});try{if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,view(state,staleMs));if(req.method==='POST'&&url.pathname==='/api/devices/register'){const b=await body(req),id=clean(b.id,160),name=clean(b.name,80);if(!id||!name)return send(res,400,{error:'device id and name required'});const old=state.devices[id]||{},now=new Date().toISOString(),device={id,name,kind:b.kind==='observer'?'observer':'factory',platform:clean(b.platform,80),hostname:clean(b.hostname,120),version:clean(b.version,40)||'0.1.0',addresses:(Array.isArray(b.addresses)?b.addresses:[]).map(x=>clean(x,80)).filter(Boolean).slice(0,20),capabilities:(Array.isArray(b.capabilities)?b.capabilities:[]).map(x=>clean(x,80)).filter(Boolean).slice(0,50),factory:{reachable:Boolean(b.factory?.reachable),url:clean(b.factory?.url,500)||null,version:clean(b.factory?.version,80)||null},workers:workers(b.workers),registeredAt:old.registeredAt||now,lastSeenAt:now};state.devices[id]=device;persist();return send(res,200,{ok:true,device,heartbeatIntervalMs:10000,staleMs})}if(req.method==='POST'&&url.pathname==='/api/observers/heartbeat'){const b=await body(req),id=clean(b.id,160);if(!id)return send(res,400,{error:'observer id required'});state.observers[id]={id,name:clean(b.name,80)||'观察者',lastSeenAt:new Date().toISOString()};persist();return send(res,200,{ok:true})}if(url.pathname.startsWith('/api/'))return send(res,404,{error:'not found'});if(req.method==='GET'&&url.pathname==='/')return send(res,200,{service:'ox-factory-device-hub',version:'0.2.0',note:'Hub 是后台设备目录；请使用原牛马工厂页面。'});return send(res,404,{error:'not found'})}catch(e){return send(res,e instanceof SyntaxError?400:422,{error:String(e.message||e)})}});return{server,token,tokenFile,stateFile}}
function args(v){const o={host:'127.0.0.1',port:8790};for(let i=0;i<v.length;i++){if(v[i]==='--host')o.host=v[++i];else if(v[i]==='--port')o.port=Number(v[++i]);else throw Error('unknown argument '+v[i])}return o}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const a=args(process.argv.slice(2)),h=createHubServer();h.server.listen(a.port,a.host,()=>console.log(`[hub] http://${a.host}:${a.port}\n[hub] token: ${h.tokenFile}`))}
